source 'http://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'haml'
gem 'mongoid'
gem 'remi-rack-staticifier', source: 'https://9fDdbcpcBdeLb5DAhPdv@gem.fury.io/gizeta/'
gem 'remi-staticify'
gem 'mini_cache'
gem 'parallel'
